"use client";
import { useState, useEffect } from "react";
import { SunderVault } from "@sunder/core";

export function useSunder() {
  const [engine, setEngine] = useState<SunderVault | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function initSunder() {
      try {
        // Dynamically import the WASM package generated by wasm-pack
        const wasm = await import("@sunder/core/pkg/sunder_core");
        await wasm.default(); // Initialize the WASM module

        const vault = new wasm.SunderVault();

        setEngine(vault);
      } catch (err) {
        console.error("Sunder Engine failed to ignite:", err);
      } finally {
        setLoading(false);
      }
    }
    initSunder();
  }, []);

  return { engine, loading };
}
